context:
  version: "0.14.27"

package:
  name: tailwindcss-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@tailwindcss/language-server/-/language-server-${{ version }}.tgz
  sha256: 33c32ed511123c754527925e5b8fbc0f21dcb2e2b8890dfd01b84ee1c83b427b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - tailwindcss-language-server &
      - exe_pid=$!
      - "trap \"kill -SIGTERM ${exe_pid}\" SIGTERM"

about:
  license: MIT
  license_file: LICENSE
  summary: Language Server Protocol implementation for Tailwind CSS
  homepage: https://github.com/tailwindlabs/tailwindcss-intellisense
  repository: https://github.com/tailwindlabs/tailwindcss-intellisense

extra:
  recipe-maintainers:
    - danielnachun
