context:
  version: "0.14.23"

package:
  name: tailwindcss-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@tailwindcss/language-server/-/language-server-${{ version }}.tgz
  sha256: 1de9c46d4e0d69552f8f9e3177f28afc93946630cf9149db77f94d00fc1c6fd5

build:
  number: 1
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - tailwindcss-language-server &
      - exe_pid=$!
      - "trap \"kill -SIGTERM ${exe_pid}\" SIGTERM"

about:
  license: MIT
  license_file: LICENSE
  summary: Language Server Protocol implementation for Tailwind CSS
  homepage: https://github.com/tailwindlabs/tailwindcss-intellisense
  repository: https://github.com/tailwindlabs/tailwindcss-intellisense

extra:
  recipe-maintainers:
    - danielnachun
